one_million = list(range(1,1000001))
print('\nHere is the minimum number from the list:')
print(min(one_million))
print('\nHere is the maximum number from the list:')
print(max(one_million))
print('\nHere is the sum of the numbers in the list')
print(sum(one_million))