
places_to_visit = ['italy','france','dubai','spain','england']
print(places_to_visit)
print(sorted(places_to_visit))
print(places_to_visit)
reversed_places_to_visit = sorted(places_to_visit,reverse=True)
print(reversed_places_to_visit)
print(places_to_visit)
places_to_visit.reverse()
print(places_to_visit)
places_to_visit.reverse()
places_to_visit.sort()
print(places_to_visit)
places_to_visit.sort(reverse=True)
print(places_to_visit)